# Generated by Django 3.0.8 on 2020-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='/static/dummyuser.jpg', null=True, upload_to='profile_images'),
        ),
    ]
