# Generated by Django 3.0.8 on 2020-11-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color_mode',
            field=models.CharField(choices=[('purple', 'purple'), ('orange', 'orange'), ('blue', 'blue'), ('teal', 'teal'), ('yellow', 'yellow'), ('red', 'red')], default='yellow', max_length=25),
        ),
    ]
