# Generated by Django 3.0.8 on 2020-11-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_color_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('tshirt', 'tshirt'), ('checkbox', 'checkbox'), ('heart', 'heart'), ('gift', 'gift')], default='tshirt', max_length=25)),
            ],
        ),
    ]
