# Generated by Django 3.0.8 on 2020-11-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_goodie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodie',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
