# Generated by Django 3.0.8 on 2020-11-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201116_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementaryLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Elementary', max_length=20)),
                ('picture', models.ImageField(default='/images/elementary/t20-logomark-white.svg', upload_to='elementary_logo')),
                ('contact', models.CharField(default='Name: Mobile Number', max_length=30)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('fb', models.CharField(default='https://www.facebook.com/jeclatT20.jgec/', max_length=100)),
                ('instagram', models.CharField(default='https://www.instagram.com/jeclat2k19/', max_length=100)),
            ],
        ),
    ]
