# Generated by Django 3.0.8 on 2020-11-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_elementarylogo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElementaryLogo',
            new_name='Customize',
        ),
    ]
