# Generated by Django 3.0.8 on 2020-11-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201116_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='picture',
            field=models.ImageField(default='/static/images/elementary/t20-logomark-white.svg', upload_to='elementary_logo'),
        ),
    ]
