# Generated by Django 3.0.8 on 2020-11-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201116_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='customize',
            name='mottos',
            field=models.CharField(default='Ready.,Active.,Creative.', max_length=50),
        ),
    ]
