# Generated by Django 3.0.8 on 2020-11-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customize_mottos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='picture',
            field=models.ImageField(default='/elementary_logo/t20-logomark-white.svg', upload_to='elementary_logo'),
        ),
    ]
