# Generated by Django 3.0.8 on 2020-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201116_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='author',
            field=models.CharField(blank=True, default='author', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, default='This Level is being uploaded', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='picture',
            field=models.ImageField(blank=True, default='/dummyuser.jpg', null=True, upload_to='level_images'),
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(blank=True, default='Uploading soon', max_length=25, null=True),
        ),
    ]
